# Generated by Django 5.2.3 on 2025-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='zip_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
